### ISSUE TITLE
`lorri daemon` hangs on launch

### ISSUE THREAD

**Issue by razvan-flavius-panda** [target/lorri#142]
When running `lorri daemon` there is not output from it, it just hangs with cursor on next line:

![](https://i.imgur.com/POiZoXc.png)

All I am doing is run `lorri daemon` in a project folder. I could reproduce this on different systems.

**Comment by Profpatsch** [comment]
If it doesn’t throw an error, it is running successfully.

You need to do an action that will tell it which nix file to watch.

Currently, there are two commands that will trigger the daemon to watch a nix file:

1) Calling `lorri direnv` in a project directory (usually done by `direnv`, but can also be done manually)
2) Calling `lorri ping_ /path/to/nix/file.nix` (`ping_` is the plumbing command to trigger the daemon, that’s why it has a trailing `_`)

We could print a message that the daemon has successfully started if it’s too confusing.

**Comment by Profpatsch** [comment]
Especially note that `lorri daemon` doesn’t fork itself into the background, because that’s generally considered a design flaw nowadays.

There’s various ways to run the daemon automatically in the background, a few are documented in https://github.com/target/lorri/issues/96, but we should add official instructions in the future.

**Comment by grahamc** [comment]
I think this is fixable by just printing a log message  like "Lorri: ready".

**Comment by razvan-flavius-panda** [comment]
Yes, please add some visual feedback that the daemon is wokring. Currently it is very confusing.
