### ISSUE TITLE
Ensure nixos-19.09 compatibility in CI

### ISSUE THREAD

**Issue by curiousleo** [target/lorri#406]
**Describe the bug**

We would like lorri to be compatible with NixOS 19.09, but our CI only builds and tests against 20.03.

More context here: https://github.com/target/lorri/pull/396#discussion_r422865040.

**To Reproduce**

1. Go to https://github.com/target/lorri/commit/d3ab9206f95c88ac692324cf8554477d28337fb6#diff-4b7dc34deb385d784093e05de88b9078R7
2. See that it says "nixos-20.03"
3. ...

**Expected behavior**

If we want to [keep supporting NixOS 19.09](https://github.com/target/lorri/pull/396#discussion_r425230375), we need to build and test lorri against 19.09 in CI.

**Comment by cole-h** [comment]
Should this just be a revert of my commit bumping to 20.03 (sorry), or would using Rust 1.37.0 from a pinned nixpkgs-mozilla overlay be sufficient to ensure 19.09 support?

If we want to use 19.09 for everything, I'd like to suggest also having 20.03 around, if only to get a cached `nixpkgs-fmt` that doesn't need to be rebuilt in CI (although, I guess cachix support for CI would mostly alleviate this issue after the first run).

**Comment by curiousleo** [comment]
> Should this just be a revert of my commit bumping to 20.03 (sorry), or would using Rust 1.37.0 from a pinned nixpkgs-mozilla overlay be sufficient to ensure 19.09 support?

First of all, no worries! This is what code review is there for in my opinion: to give context - it's not obvious that 19.09 was a conscious choice of channel to build against just from the build setup.

Secondly, I think that the most obvious way to ensure compatibility with 19.09 is to build and test against 19.09. I think that building against Rust 1.37.0 with `nixpkgs-mozilla` overlay and other packages coming from 20.03 makes it _very likely_ that lorri is 19.09-compatible, but there's no guarantee.

> If we want to use 19.09 for everything, I'd like to suggest also having 20.03 around, if only to get a cached `nixpkgs-fmt` that doesn't need to be rebuilt in CI (although, I guess cachix support for CI would mostly alleviate this issue after the first run).

A compromise could be to have a more minimal build on 19.09. We want to ensure that lorri builds and runs correctly there, so we should compile and run tests. But we can move formatting, linting (`nixpkgs-fmt`) and everything else to run only on 20.03. This assumes that lorri's code is compatible with both the Rust version in 19.09 and the Rust version in 20.03. I haven't checked, but I believe that this is the case.

Thoughts @Profpatsch @grahamc?

**Comment by cole-h** [comment]
1.37.0 on 20.03 doesn't guarantee compatibility, you're right... Very good point (no matter how close it gets).

Lorri is indeed compatible with both 1.37.0 (19.09) and 1.41.0 (20.03) -- tested with `rustup run 1.37.0 cargo build` and `rustup run 1.41.0 cargo build`.

I like the compromise of having a more minimal build, e.g. separating out the development tools from the build tools -- mostly because that will sidestep the problem of having to spend X minutes building a linter in CI. If nobody disagrees with this approach, I think I can find some time to work on it (depending on how smooth my current transition to NixOS is -- slowly but surely...).

**Comment by curiousleo** [comment]
> Lorri is indeed compatible with both 1.37.0 (19.09) and 1.41.0 (20.03) -- tested with `rustup run 1.37.0 cargo build` and `rustup run 1.41.0 cargo build`.

Thanks for the confirmation!

> I like the compromise of having a more minimal build, e.g. separating out the development tools from the build tools -- mostly because that will sidestep the problem of having to spend X minutes building a linter in CI. If nobody disagrees with this approach, I think I can find some time to work on it (depending on how smooth my current transition to NixOS is -- slowly but surely...).

That would be awesome! @Profpatsch @grahamc any objections?

**Comment by curiousleo** [comment]
@cole-h of course if you get stuck or find that you don't have the time, or have any questions, please post them here, we're happy to help.

**Comment by Profpatsch** [comment]
> A compromise could be to have a more minimal build on 19.09. We want to
ensure that lorri builds and runs correctly there, so we should compile and
run tests. But we can move formatting, linting (nixpkgs-fmt) and everything
else to run only on 20.03. This assumes that lorri's code is compatible
with both the Rust version in 19.09 and the Rust version in 20.03. I
haven't checked, but I believe that this is the case.

I see two different use-cases here:

* Being able to override the `nixpkgs.lorri` version to work with current
master, in order to not have to wait on a new lorri release in nixpkgs.
* Being able to build lorri with the stable rustc and nix from 19.09

Both should be checked on our CI, because they are valid use-cases I’d like
to support in order to avoid user annoyance (“why is it impossible to build
this program with a stable compiler that is not even half a year old”).

We can restrict the 19.09-specific checks to those two use-cases and run
them in a parallel CI job.

**Comment by Profpatsch** [comment]
> We can restrict the 19.09-specific checks to those two use-cases and run
them in a parallel CI job.

Maybe we should even go back further (e.g. to 19.03) and see how far back
we can still reasonably support, then define a minimum timeframe we want to
support (I’d like the current and the previous stable nixos release) and a
bunch of releases we support if there’s only trivial changes we must make
to support them (i.e. no #ifdef horrors).

**Comment by cole-h** [comment]
Hi guys,

Just a little update: I have not started working on this... *yet*. I'm almost happy (or as happy as I will be) with my NixOS setup; once I'm mostly done, that'll free up some time to work on other things, like this.

Sorry for the delay!

---

I just did a little test, and the furthest back we can reasonably support (without some more elbow grease) is 19.09. This is because `rustPackages` was introduced in https://github.com/nixos/nixpkgs/commit/912dca193aee9da77a4d429285db53729d81aa3d, which is not present on 19.03 or earlier.

@Profpatsch I'm unclear on what you mean in your first use-case of overriding `nixpkgs.lorri` (or rather, how that would be testable in CI). Could you maybe explain what you would like to see, CI-wise?

**Comment by Profpatsch** [comment]
Thank you for the update!

**Comment by curiousleo** [comment]
@Profpatsch it looks like you may have missed @cole-h's question:
> @Profpatsch I'm unclear on what you mean in your first use-case of overriding `nixpkgs.lorri` (or rather, how that would be testable in CI). Could you maybe explain what you would like to see, CI-wise?

**Comment by Profpatsch** [comment]
I totally have, Gmail displays the bar so prominently that my eyes must have thought it’s the end of the message and the rest is footer.

> @Profpatsch I'm unclear on what you mean in your first use-case of overriding `nixpkgs.lorri` (or rather, how that would be testable in CI). Could you maybe explain what you would like to see, CI-wise?

We could fetch the current nixpkgs stable channel and apply our `default.nix` onto it. Shouldn’t be too hard to implement, I can take a look once the general setup is there.

> I just did a little test, and the furthest back we can reasonably support (without some more elbow grease) is 19.09. This is because `rustPackages` was introduced in [NixOS/nixpkgs@912dca1](https://github.com/NixOS/nixpkgs/commit/912dca193aee9da77a4d429285db53729d81aa3d), which is not present on 19.03 or earlier.

Great, then let’s do that.
